name: Build APK

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build the App
        run: chmod +x gradlew && ./gradlew assembleDebug

      - name: Upload the APK
        uses: actions/upload-artifact@v4
        with:
          name: S26-Morph-App
          path: app/build/outputs/apk/debug/*.apk
